[package]
name = "packet_inspector"
version.workspace = true
edition.workspace = true
description = "A simple Minecraft proxy for inspecting packets."

[features]
default = ["gui"]
gui = ["syntect", "serde"]
cli = []

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
valence = { workspace = true }
time = { workspace = true, features = ["local-offset"] }

tracing-subscriber = { workspace = true }
egui = { workspace = true }
eframe = { workspace = true, features = ["persistence", "wgpu"] }
egui_dock = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
enum-map = { workspace = true, features = ["serde"] }
syntect = { workspace = true, default-features = false, optional = true, features = [
    "default-fancy",
] }

[dependencies.serde]
workspace = true
features = ["derive"]
optional = true

[build-dependencies]
syn = "2.0.18"
anyhow = "1.0.71"
heck = "0.4.1"
proc-macro2 = "1.0.60"
quote = "1.0.28"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
